# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("中国天气信息查询程序")
        Form.resize(400, 300)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.city_edit = QtWidgets.QLineEdit(Form)
        self.city_edit.setObjectName("city_edit")
        self.horizontalLayout.addWidget(self.city_edit)
        self.search_button = QtWidgets.QPushButton(Form)
        self.search_button.setObjectName("search_button")
        self.horizontalLayout.addWidget(self.search_button)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.info_text = QtWidgets.QTextEdit(Form)
        self.info_text.setObjectName("info_text")
        self.verticalLayout_5.addWidget(self.info_text)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "中国天气信息查询程序"))
        self.label.setText(_translate("Form", "中国天气信息查询程序"))
        self.search_button.setText(_translate("Form", "查询"))
